tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack@0.0.8:KGahbNlLCY19QUebUzdLbA==
    - Pivotal.vscode-spring-boot@1.23.0:1iLvjTfznJrV611qRUeOHg==